### PR TITLE
revised logo

### PR DESCRIPTION
**Pull request by bmcfee**
Taking a stab at a new logo graphic that's maybe a bit less busy.

### CODE REVIEW

**Comment by bmcfee** [comment]
image

using 3 colors out of the `plasma` colormap.  Anyone have suggestions?  @lostanlen @justinsalamon ?

**Comment by bmcfee** [comment]
And here it is in magma:

image

**Comment by justinsalamon** [comment]
I like the idea of simplifying the logo! I wonder whether this design achieves that though? Maybe something with less lines?

**Comment by bmcfee** [comment]
Fair enough -- I think this design is simpler.  It might have comparable line complexity, but it comes across as less busy (IMO) by way of symmetry.  I'm open to suggestions for improvement though!

**Comment by bmcfee** [comment]
Here are a few more variations:

librosa_logo_condensed

librosa_logo_text

**Comment by lostanlen** [comment]
the two-color lettering looks great!

**Comment by bmcfee** [comment]
One more draft, having revised the center squiggle after discussion offline.

librosa_logo_condensed-redone

librosa_logo_text

**Comment by justinsalamon** [comment]
Still feels too busy for me. I'd try and go with a design with only 2 "circles" (inner and outer), rather than 3. Just my opinion though ¯\_(ツ)_/¯

**Comment by bmcfee** [comment]
One more go at it -- I think i prefer the 3-color version.

librosa_logo_simpler-text
librosa_logo_simpler

**Comment by bmcfee** [comment]
And a three-color version just for fun:

librosa_logo_simpler3

librosa_logo_simpler-text

**Comment by bmcfee** [comment]
@lostanlen and I iterated on this a bit, and I think it's converged.  Final proposals are in the PR now, but here are snapshots:

librosa_logo_text
librosa_logo

**Comment by justinsalamon** [comment]
I think that's somewhat better, but, to be totally honest, I'm still not a fan of the design. Something in the strokes feels outdated/complicated. To be more concrete, here are examples of "roses" I like better as logos:

* https://www.vectorstock.com/royalty-free-vector/rose-icon-valentine-symbolic-vector-16342791
* https://www.vectorstock.com/royalty-free-vector/rose-flower-icon-vector-3720361
* https://www.flaticon.com/free-icon/rose_1898786#term=rose&page=1&position=9
* https://www.shutterstock.com/image-vector/rose-icon-flower-symbol-plant-pictogram-1029365620
* https://www.shutterstock.com/image-vector/rose-icon-257336641

As a non-expert I lack the vocabulary to explain what is it in these designs that I find more appealing, but I think if you look at these you'll see they share a common visual language that the current proposed design lacks. Just my 2c.

**Comment by bmcfee** [comment]
No accounting for taste, I guess.  I'm not won over by any of the alternates you suggest, which all seem a bit clunky or generic IMO.

**Comment by justinsalamon** [comment]
¯\_(ツ)_/¯ 

I guess if I had to try and verbalize my thinking, contemporary design tends to be relatively minimalistic: flatter, fewer lines, fewer colors, and whatever lines/colors are used are kept consistent. In contrast, the current proposal has many lines, with varying stroke thickness (between lines but also within each line).

It might be easier to illustrate my thinking by looking at how some logos have evolved over time:

image

image

image

Like anything it's just a trend and what a "contemporary" looks like will continue to change (who knows, maybe skeuomorphism will make a comeback :P). More important still, "there's no point arguing over taste and smell", as they say in hebrew (don't ask me why smell... maybe because it rhymes).

Aaaanyway, I guess what I'm saying is that the current proposal doesn't feel congruent with my perception of contemporary visual language when it comes to logos/brands, but I'm just one data point, which brings me back to how I started this comment: ¯\_(ツ)_/¯

**Comment by bmcfee** [comment]
Hey, I'm going on about this because i value your opinion!  I agree with everything you say in principle, but I'm not so convinced that it applies to that design (exactly two strokes, replicated, and three flat colors).

Is it perhaps the use of negative space that you're objecting to?  I could see how that might come across as busy, but I don't think it's excessively so.  Just for funsies, I made some filled-in versions of the above which may be more to your liking (colors need work though):

librosa_logo_text_filled
librosa_logo_filled

**Comment by justinsalamon** [comment]
That does somehow feel less busy, though ideally the logo should look good in its original colors but also inverted colors, as well as in black and white, along the lines of:

image
image

I think a good logo should naturally fit in with:

image

i.e. it should be simple and quickly identifiable in any color combination.

Anyway, easier said than done. I'd try to cobble something up myself now but DCASE 😬

**Comment by justinsalamon** [comment]
OK couldn't help myself, here's a super quick hack:

librosa_draft

The actual shape/colors/font/composition are all pretty poor, but just as an example of a minimalist concept.

**Comment by justinsalamon** [comment]
Maybe a Courier "L" would look nicer (more like code):

librosa_draft2

**Comment by bmcfee** [comment]
I'll be honest -- I don't like either of those, and I don't think this conversation is headed anywhere productive.  We don't need to make a logo that fits on an iphone home screen (which appears to be the context you're invoking above), but I do think the proposed design would be visibly salient there if rendered down to black/white.

**Comment by lostanlen** [comment]
I think that this last one by @bmcfee (https://github.com/librosa/librosa_media/pull/2#issuecomment-511066726) checks all the important boxes:
* is close to square. Will nicely fit a GitHub organization handle
* is close to round. Will nicely fit a twitter handle
* a single version works on both white background and grey background
* the plasma colormap makes is deuteranopia-friendly, tritanopia-friendly, and protanopia-friendly
* is figurative enough to be recognizable as rose-related ...
* ... but not figurative to the point that people would think that we actually grow roses for a business

So i'm on board with merging this. We can always revisit this choice after we've seen how this logo has been received IRL

**Comment by bmcfee** [comment]
Thanks all -- I still prefer the non-filled version https://github.com/librosa/librosa_media/pull/2#issuecomment-510981996 which I think will work better on transparent sticker backgrounds / website.  Is that okay?

**Comment by lostanlen** [comment]
@bmcfee yes, that works.  ~As written earlier, i would be a little bit careful about the exact orientation of the logo, so that it nicely fits a hexagon whose bottom side is perfectly horizontal. But aside from that~ it's good to go IMHO :shipit: 
EDIT: actually, it's fine.

**Comment by bmcfee** [comment]
Ok, thanks again for everyone's input!  I'm declaring the bike shed closed for now, and as @lostanlen says, we can revisit later if need be.

**Pull request merged**
